PS1="\n\u@iMac:\w \[$CYAN\]\$(vcprompt)\[$NO_COLOR\]\n→ "
# PS1="\n\[$GREEN\]\$(~/.rvm/bin/rvm-prompt i v p g)\[$NO_COLOR\] $PS1"
RUBY_V="asdf current ruby | cut -d '(' -f 1 | xargs"
NODE_V="asdf current nodejs | cut -d '(' -f 1 | xargs"
RUBY_PS="\[$RED\]\$($RUBY_V)\[$NO_COLOR\] "
NODE_PS="\[$GREEN\]\$($NODE_V)\[$NO_COLOR\] "
PS1="\n$RUBY_PS$NODE_PS $PS1"